In [8]:
import numpy as np
#problem 1
# STEP 1: Define the coefficient matrix (A)
# Each row represents one of the three intercepted signal relationships.
# Row 1: 2(m1) + 1(m2) + 1(m3) = 36
# Row 2: -1(m1) + 2(m2) - 1(m3) = -11
# Row 3: 3(m1) - 1(m2) + 2(m3) = 47
A = np.array([
    [2, 1, 1],
    [-1, 2, -1],
    [3, -1, 2]
])

# STEP 2: Define the constant vector (b)
# This represents the intercepted output values (the results of the equations).
b = np.array([36, -11, 47])

# STEP 3: Decrypt the message
# We find the original packets (m) by calculating the inverse of A 
# and multiplying it by b (m = A^-1 * b). 
# The '@' operator in NumPy performs matrix multiplication.
m = np.linalg.inv(A) @ b

print("Decrypted Message Packets (m1, m2, m3):")
print(m)

Decrypted Message Packets (m1, m2, m3):
[-64.   0. 128.]


In [4]:
import numpy as np
#problem 2
# STEP 1: Define the nutrient matrix (A)
# Each column represents a Pellet (A, B, C, D)
# Each row represents a nutrient (Protein, Carbs, Fat, Vitamins)
A = np.array([
    [30, 20, 50, 10], # Protein content
    [40, 50, 20, 30], # Carbohydrate content
    [10, 30, 20, 40], # Fat content
    [20, 10, 40, 50]  # Vitamin content
])

# STEP 2: Define the target nutrient vector (b)
# These are the exact grams/mg the primate needs daily
b = np.array([145, 210, 115, 170])

# STEP 3: Solve for the number of servings (x)
# x = A^-1 * b
# This tells us exactly how many 100g servings of each pellet to mix.
x = np.linalg.inv(A) @ b

print("Required servings of Pellets A, B, C, and D (per 100g):")
print(x)    

Required servings of Pellets A, B, C, and D (per 100g):
[3.58125 0.20625 0.3375  1.65625]


In [5]:
import numpy as np
#problem 3
# STEP 1: Define the 3x3 Consumption Matrix (C)
# Columns represent the sector providing the input (E, M, S)
# Rows represent the sector receiving the input
C = np.array([
    [0.2, 0.3, 0.1], # Inputs required from Energy
    [0.4, 0.1, 0.2], # Inputs required from Manufacturing
    [0.1, 0.2, 0.1]  # Inputs required from Services
])

# STEP 2: Create the 3x3 Identity Matrix (I)
I = np.eye(3)

# STEP 3: Define the external demand vector (d) in millions
d = np.array([500, 800, 600])

# STEP 4: Compute the matrix (I - C)
# This represents the net output available for the open market
A_leontief = I - C

# STEP 5: Solve for total production (x)
# x = (I - C)^-1 * d
x_production = np.linalg.inv(A_leontief) @ d

print("Total Production Required (in millions) for Energy, Manufacturing, and Services:")
print(x_production)

Total Production Required (in millions) for Energy, Manufacturing, and Services:
[1457.73195876 1810.30927835 1230.92783505]


In [6]:
import numpy as np
#problem 4
# STEP 1: Assemble the 4x4 Resistance Matrix (R)
# Each row is a loop equation. 
# We explicitly place a 0 wherever a current is not part of that loop.
R = np.array([
    [10, -2, -3,  0],  # Loop 1
    [-2, 15,  0, -4],  # Loop 2
    [-3,  0, 12, -5],  # Loop 3
    [ 0, -4, -5, 20]   # Loop 4
])

# STEP 2: Define the Voltage Vector (V)
# This holds the constant voltage sums from the right side of the equations.
V = np.array([12, 5, 0, -10])

# STEP 3: Solve for the Currents (I)
# Using the matrix inverse method: I = R^-1 * V
# The inverse of the resistance matrix multiplied by the voltages gives the currents.
currents = np.linalg.inv(R) @ V

print("Currents flowing through Loops I1, I2, I3, and I4 (in Amperes):")
print(currents)

Currents flowing through Loops I1, I2, I3, and I4 (in Amperes):
[ 1.3359826   0.4120117   0.17860088 -0.37294744]


In [7]:
import numpy as np
#problem 5
# STEP 1: Define the recorded time intervals (x) and altitudes (y)
x_vals = np.array([-2, -1, 1, 2, 3])
y_vals = np.array([59, 17, 5, 11, 49])

# STEP 2: Construct the 5x5 Vandermonde Matrix (A)
# Each column represents a power of x: x^0, x^1, x^2, x^3, x^4
# We use a list comprehension to calculate this automatically for each x
A = np.array([
    [x**0, x**1, x**2, x**3, x**4] for x in x_vals
])

# Or manually:
# A = np.array([
#     [1, -2,  4, -8,  16],
#     [1, -1,  1, -1,   1],
#     [1,  1,  1,  1,   1],
#     [1,  2,  4,  8,  16],
#     [1,  3,  9, 27,  81]
# ])

# STEP 3: Solve for the polynomial coefficients (a, b, c, d, e)
# coefficients = A^-1 * y_vals
coefficients = np.linalg.inv(A) @ y_vals

print("Polynomial Coefficients (a, b, c, d, e):")
print(coefficients)

Polynomial Coefficients (a, b, c, d, e):
[ 7. -4.  3. -2.  1.]
