In [1]:
import numpy as np

def custom_gaussian_elimination(A, b):
    # Convert to float to ensure precision during division
    A = A.astype(float)
    b = b.astype(float).reshape(-1, 1)
    n = len(b)
    
    # Combine into an augmented matrix
    augmented = np.hstack((A, b))
    
    print("Step 0: Initial Augmented Matrix")
    print(augmented)
    print("-" * 30)

    # --- Forward Elimination ---
    for i in range(n):
        # Pivoting to ensure the largest absolute value is at the pivot position
        pivot_row = np.argmax(np.abs(augmented[i:, i])) + i
        augmented[[i, pivot_row]] = augmented[[pivot_row, i]]
        
        for j in range(i + 1, n):
            factor = augmented[j, i] / augmented[i, i]
            # Zero out the element below the pivot
            augmented[j, i:] = augmented[j, i:] - factor * augmented[i, i:]
            
            print(f"Eliminating column {i}, row {j}:")
            print(np.round(augmented, 4))
            print("-" * 20)

    # --- Back Substitution ---
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (augmented[i, -1] - np.dot(augmented[i, i+1:n], x[i+1:n])) / augmented[i, i]
        
    return x

# Problem Setup
A1 = np.array([[2, 1, 1], [-1, 2, -1], [3, -1, 2]])
b1 = np.array([36, -11, 47])

# Run Solver
m_packets = custom_gaussian_elimination(A1, b1)

print("Decrypted Data Packets (m1, m2, m3):")
print(m_packets)

Step 0: Initial Augmented Matrix
[[  2.   1.   1.  36.]
 [ -1.   2.  -1. -11.]
 [  3.  -1.   2.  47.]]
------------------------------
Eliminating column 0, row 1:
[[ 3.     -1.      2.     47.    ]
 [ 0.      1.6667 -0.3333  4.6667]
 [ 2.      1.      1.     36.    ]]
--------------------
Eliminating column 0, row 2:
[[ 3.     -1.      2.     47.    ]
 [ 0.      1.6667 -0.3333  4.6667]
 [ 0.      1.6667 -0.3333  4.6667]]
--------------------
Eliminating column 1, row 2:
[[ 3.     -1.      2.     47.    ]
 [ 0.      1.6667 -0.3333  4.6667]
 [ 0.      0.      0.      0.    ]]
--------------------
Decrypted Data Packets (m1, m2, m3):
[-12.2  12.4  48. ]


In [2]:
import numpy as np

def custom_gaussian_elimination(A, b):
    A = A.astype(float)
    b = b.astype(float).reshape(-1, 1)
    n = len(b)
    augmented = np.hstack((A, b))
    
    print("Initial Augmented Matrix:")
    print(augmented)
    print("-" * 30)

    # --- Forward Elimination ---
    for i in range(n):
        # Pivoting
        pivot_row = np.argmax(np.abs(augmented[i:, i])) + i
        augmented[[i, pivot_row]] = augmented[[pivot_row, i]]
        
        for j in range(i + 1, n):
            if augmented[i, i] == 0: continue
            factor = augmented[j, i] / augmented[i, i]
            augmented[j, i:] = augmented[j, i:] - factor * augmented[i, i:]
            
            print(f"Step: Zeroing column {i}, row {j}")
            print(np.round(augmented, 2))
            print("-" * 20)

    # --- Back Substitution ---
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (augmented[i, -1] - np.dot(augmented[i, i+1:n], x[i+1:n])) / augmented[i, i]
        
    return x

# Setup Data for Problem 2
A2 = np.array([
    [30, 20, 50, 10],
    [40, 50, 20, 30],
    [10, 30, 20, 40],
    [20, 10, 40, 50]
])
b2 = np.array([145, 210, 115, 170])

# Execute Solver
servings = custom_gaussian_elimination(A2, b2)

print("Servings required (x1, x2, x3, x4):")
print(servings)

Initial Augmented Matrix:
[[ 30.  20.  50.  10. 145.]
 [ 40.  50.  20.  30. 210.]
 [ 10.  30.  20.  40. 115.]
 [ 20.  10.  40.  50. 170.]]
------------------------------
Step: Zeroing column 0, row 1
[[ 40.   50.   20.   30.  210. ]
 [  0.  -17.5  35.  -12.5 -12.5]
 [ 10.   30.   20.   40.  115. ]
 [ 20.   10.   40.   50.  170. ]]
--------------------
Step: Zeroing column 0, row 2
[[ 40.   50.   20.   30.  210. ]
 [  0.  -17.5  35.  -12.5 -12.5]
 [  0.   17.5  15.   32.5  62.5]
 [ 20.   10.   40.   50.  170. ]]
--------------------
Step: Zeroing column 0, row 3
[[ 40.   50.   20.   30.  210. ]
 [  0.  -17.5  35.  -12.5 -12.5]
 [  0.   17.5  15.   32.5  62.5]
 [  0.  -15.   30.   35.   65. ]]
--------------------
Step: Zeroing column 1, row 2
[[ 40.   50.   20.   30.  210. ]
 [  0.  -17.5  35.  -12.5 -12.5]
 [  0.    0.   50.   20.   50. ]
 [  0.  -15.   30.   35.   65. ]]
--------------------
Step: Zeroing column 1, row 3
[[ 40.    50.    20.    30.   210.  ]
 [  0.   -17.5   35.   -12

In [3]:
import numpy as np

# 1. Define the consumption matrix C
# Rows: E, M, S | Columns: E, M, S
C = np.array([
    [0.20, 0.30, 0.10],
    [0.40, 0.10, 0.20],
    [0.10, 0.20, 0.10]
])

# 2. Create the Identity matrix
I = np.eye(3)

# 3. Compute (I - C)
A3 = I - C

# 4. Define the demand vector d
b3 = np.array([500, 800, 600])

# Using our custom Gaussian elimination function (defined in previous problems)
# Note: Ensure the function custom_gaussian_elimination is defined in your notebook
total_production = custom_gaussian_elimination(A3, b3)

print("Total Production Vector (x):")
print(total_production)

Initial Augmented Matrix:
[[ 8.e-01 -3.e-01 -1.e-01  5.e+02]
 [-4.e-01  9.e-01 -2.e-01  8.e+02]
 [-1.e-01 -2.e-01  9.e-01  6.e+02]]
------------------------------
Step: Zeroing column 0, row 1
[[ 8.00e-01 -3.00e-01 -1.00e-01  5.00e+02]
 [ 0.00e+00  7.50e-01 -2.50e-01  1.05e+03]
 [-1.00e-01 -2.00e-01  9.00e-01  6.00e+02]]
--------------------
Step: Zeroing column 0, row 2
[[ 8.000e-01 -3.000e-01 -1.000e-01  5.000e+02]
 [ 0.000e+00  7.500e-01 -2.500e-01  1.050e+03]
 [ 0.000e+00 -2.400e-01  8.900e-01  6.625e+02]]
--------------------
Step: Zeroing column 1, row 2
[[ 8.00e-01 -3.00e-01 -1.00e-01  5.00e+02]
 [ 0.00e+00  7.50e-01 -2.50e-01  1.05e+03]
 [ 0.00e+00  0.00e+00  8.10e-01  9.95e+02]]
--------------------
Total Production Vector (x):
[1457.73195876 1810.30927835 1230.92783505]


In [4]:
import numpy as np

# Define the Resistance Matrix R
# Note: zeros are placed where loops do not share a direct component
R = np.array([
    [10, -2, -3,  0],
    [-2, 15,  0, -4],
    [-3,  0, 12, -5],
    [ 0, -4, -5, 20]
])

# Define the Voltage Vector V
V = np.array([12, 5, 0, -10])

# Solve using our custom function to see step-by-step augmented matrices
# Ensure custom_gaussian_elimination is defined in your notebook
loop_currents = custom_gaussian_elimination(R, V)

print("Calculated Loop Currents (I1, I2, I3, I4):")
print(loop_currents)

Initial Augmented Matrix:
[[ 10.  -2.  -3.   0.  12.]
 [ -2.  15.   0.  -4.   5.]
 [ -3.   0.  12.  -5.   0.]
 [  0.  -4.  -5.  20. -10.]]
------------------------------
Step: Zeroing column 0, row 1
[[ 10.   -2.   -3.    0.   12. ]
 [  0.   14.6  -0.6  -4.    7.4]
 [ -3.    0.   12.   -5.    0. ]
 [  0.   -4.   -5.   20.  -10. ]]
--------------------
Step: Zeroing column 0, row 2
[[ 10.   -2.   -3.    0.   12. ]
 [  0.   14.6  -0.6  -4.    7.4]
 [  0.   -0.6  11.1  -5.    3.6]
 [  0.   -4.   -5.   20.  -10. ]]
--------------------
Step: Zeroing column 0, row 3
[[ 10.   -2.   -3.    0.   12. ]
 [  0.   14.6  -0.6  -4.    7.4]
 [  0.   -0.6  11.1  -5.    3.6]
 [  0.   -4.   -5.   20.  -10. ]]
--------------------
Step: Zeroing column 1, row 2
[[ 10.    -2.    -3.     0.    12.  ]
 [  0.    14.6   -0.6   -4.     7.4 ]
 [  0.     0.    11.08  -5.16   3.9 ]
 [  0.    -4.    -5.    20.   -10.  ]]
--------------------
Step: Zeroing column 1, row 3
[[10.   -2.   -3.    0.   12.  ]
 [ 0.   14.

In [5]:
import numpy as np

# Data points provided
x_points = np.array([-2, -1, 1, 2, 3])
y_points = np.array([59, 17, 5, 11, 49])

# 1. Construct the 5x5 Vandermonde Matrix
# Each row is [x^0, x^1, x^2, x^3, x^4]
A5 = np.array([[x**i for i in range(5)] for x in x_points])

# 2. Define the constants vector b
b5 = y_points

# 3. Solve the system
# Ensure your custom_gaussian_elimination function is defined in your notebook
coefficients = custom_gaussian_elimination(A5, b5)

print("Polynomial Coefficients [a, b, c, d, e]:")
print(np.round(coefficients, 4))

Initial Augmented Matrix:
[[ 1. -2.  4. -8. 16. 59.]
 [ 1. -1.  1. -1.  1. 17.]
 [ 1.  1.  1.  1.  1.  5.]
 [ 1.  2.  4.  8. 16. 11.]
 [ 1.  3.  9. 27. 81. 49.]]
------------------------------
Step: Zeroing column 0, row 1
[[  1.  -2.   4.  -8.  16.  59.]
 [  0.   1.  -3.   7. -15. -42.]
 [  1.   1.   1.   1.   1.   5.]
 [  1.   2.   4.   8.  16.  11.]
 [  1.   3.   9.  27.  81.  49.]]
--------------------
Step: Zeroing column 0, row 2
[[  1.  -2.   4.  -8.  16.  59.]
 [  0.   1.  -3.   7. -15. -42.]
 [  0.   3.  -3.   9. -15. -54.]
 [  1.   2.   4.   8.  16.  11.]
 [  1.   3.   9.  27.  81.  49.]]
--------------------
Step: Zeroing column 0, row 3
[[  1.  -2.   4.  -8.  16.  59.]
 [  0.   1.  -3.   7. -15. -42.]
 [  0.   3.  -3.   9. -15. -54.]
 [  0.   4.   0.  16.   0. -48.]
 [  1.   3.   9.  27.  81.  49.]]
--------------------
Step: Zeroing column 0, row 4
[[  1.  -2.   4.  -8.  16.  59.]
 [  0.   1.  -3.   7. -15. -42.]
 [  0.   3.  -3.   9. -15. -54.]
 [  0.   4.   0.  16.   0. 