In [11]:
import numpy as np

def gaussian_elimination_and_back_sub(A, B):
    # Combine A and B into an augmented matrix
    matrix = np.column_stack((A.astype(float), B.astype(float)))
    rows = len(B)
    
    print("--- PHASE 1: INITIAL AUGMENTED MATRIX ---")
    print(np.round(matrix, 4))
    print("\n" + "=" * 50 + "\n")
    
    # --- PHASE 2: FORWARD ELIMINATION ---
    print("--- PHASE 2: FORWARD ELIMINATION ---")
    for i in range(rows):
        # Step A: Make the current pivot 1
        pivot = matrix[i][i]
        
        # Safety check to prevent dividing by zero
        if pivot == 0:
            print(f"Zero pivot encountered at row {i+1}. Please reorder your equations!")
            return None
            
        matrix[i] = matrix[i] / pivot
        print(f"\nStep {i+1}A: Scale Row {i+1} so the pivot is 1")
        print(np.round(matrix, 4))
        
        # Step B: Eliminate the numbers below the pivot
        for j in range(i + 1, rows):
            factor = matrix[j][i]
            matrix[j] = matrix[j] - factor * matrix[i]
            
        if i < rows - 1: # Don't print this for the very last row
            print(f"Step {i+1}B: Clear numbers below the pivot in Column {i+1}")
            print(np.round(matrix, 4))
            
    print("\nFinal Matrix in Row Echelon Form:")
    print(np.round(matrix, 4))
    print("\n" + "=" * 50 + "\n")
    
    # --- PHASE 3: CUSTOM BACK-SUBSTITUTION ---
    print("--- PHASE 3: MANUAL BACK-SUBSTITUTION ---")
    
    # Create an empty array to hold our final answers
    solution = np.zeros(rows)
    
    # Loop backwards from the bottom row up to the top row
    for i in range(rows - 1, -1, -1):
        # Start with the constant on the far right
        current_val = matrix[i][-1]
        
        # Subtract the variables we have already solved for
        for j in range(i + 1, rows):
            current_val -= matrix[i][j] * solution[j]
            
        solution[i] = current_val
        print(f"w{i+1} = {solution[i]:.4f}")
        
    return solution


# ==============================================================
# 🛑 ACTION REQUIRED: PUT YOUR EXACT NUMBERS HERE 🛑
# ==============================================================

# The coefficient matrix (left side of the equations)
A = np.array([
    [ 4,  2, -1,  3,  1],
    [ 2,  5,  2, -1,  3],
    [-1,  2,  6,  2, -2],
    [ 3, -1,  2,  7,  1],
    [ 1,  3, -2,  1,  8]
])

# The constants vector (right side of the equations)
B = np.array([15, 21, 9, 19, 17])


# 1. Run our custom step-by-step solver
print("Running custom solver...\n")
my_solution = gaussian_elimination_and_back_sub(A, B)

# 2. Run Numpy's exact solver just to double check our work
print("\n" + "=" * 50)
print("--- PHASE 4: VERIFICATION WITH NUMPY ---")
if my_solution is not None:
    numpy_solution = np.linalg.solve(A, B)
    for i in range(len(numpy_solution)):
        print(f"w{i+1} = {numpy_solution[i]:.4f}")

Running custom solver...

--- PHASE 1: INITIAL AUGMENTED MATRIX ---
[[ 4.  2. -1.  3.  1. 15.]
 [ 2.  5.  2. -1.  3. 21.]
 [-1.  2.  6.  2. -2.  9.]
 [ 3. -1.  2.  7.  1. 19.]
 [ 1.  3. -2.  1.  8. 17.]]


--- PHASE 2: FORWARD ELIMINATION ---

Step 1A: Scale Row 1 so the pivot is 1
[[ 1.    0.5  -0.25  0.75  0.25  3.75]
 [ 2.    5.    2.   -1.    3.   21.  ]
 [-1.    2.    6.    2.   -2.    9.  ]
 [ 3.   -1.    2.    7.    1.   19.  ]
 [ 1.    3.   -2.    1.    8.   17.  ]]
Step 1B: Clear numbers below the pivot in Column 1
[[ 1.    0.5  -0.25  0.75  0.25  3.75]
 [ 0.    4.    2.5  -2.5   2.5  13.5 ]
 [ 0.    2.5   5.75  2.75 -1.75 12.75]
 [ 0.   -2.5   2.75  4.75  0.25  7.75]
 [ 0.    2.5  -1.75  0.25  7.75 13.25]]

Step 2A: Scale Row 2 so the pivot is 1
[[ 1.     0.5   -0.25   0.75   0.25   3.75 ]
 [ 0.     1.     0.625 -0.625  0.625  3.375]
 [ 0.     2.5    5.75   2.75  -1.75  12.75 ]
 [ 0.    -2.5    2.75   4.75   0.25   7.75 ]
 [ 0.     2.5   -1.75   0.25   7.75  13.25 ]]
Step 2B:

In [17]:
# --- Complete Step-by-Step Interpolation Solver ---
# This script programmatically solves and prints the manual steps 
# for linear and quadratic interpolation using specific data points.

def solve_part_a():
    """Solves Part 1: Estimating the voltage at distance d = 55 cm."""
    print("==================================================")
    print("PART 1: Estimation at d = 55 cm")
    print("==================================================\n")
    
    # ==========================================
    # --- A. Linear Interpolation ---
    # Linear interpolation uses the formula: y = y0 + (y1 - y0)/(x1 - x0) * (x - x0)
    # We use the two closest data points bounding 55 cm: 50 cm and 60 cm.
    # ==========================================
    print("--- A. Linear Interpolation ---")
    d0, v0 = 50, 1.61  # Point 1 (x0, y0)
    d1, v1 = 60, 1.44  # Point 2 (x1, y1)
    d_target = 55      # The distance we want to estimate the voltage for
    
    print(f"1. Points used: ({d0}, {v0}) and ({d1}, {v1})")
    print(f"2. Formula: V(55) = {v0} + (({v1} - {v0}) / ({d1} - {d0})) * ({d_target} - {d0})")
    
    # Break down the calculation into steps for clarity
    numerator = v1 - v0         # Change in voltage (y1 - y0)
    denominator = d1 - d0       # Change in distance (x1 - x0)
    multiplier = d_target - d0  # Distance from the lower bound (x - x0)
    slope = numerator / denominator # Rate of change (m)
    
    print(f"3. Calculate slope: {numerator:.2f} / {denominator} = {slope:.3f}")
    
    # Calculate final linear estimate
    v_linear = v0 + slope * multiplier
    print(f"4. Final Calculation: {v0} + ({slope:.3f} * {multiplier})")
    print(f"--> ANSWER: V(55) = {v_linear:.3f} V\n")
    
    
    # ==========================================
    # --- B. Quadratic Interpolation ---
    # Fits a parabola (y = a0 + a1*x + a2*x^2) using the 3 closest points:
    # 40 cm, 50 cm, and 60 cm. We solve for coefficients a0, a1, a2.
    # ==========================================
    print("--- B. Quadratic Interpolation ---")
    d1_q, v1_q = 40, 1.82 # Point 1
    d2_q, v2_q = 50, 1.61 # Point 2
    d3_q, v3_q = 60, 1.44 # Point 3
    
    print(f"1. Points used: ({d1_q}, {v1_q}), ({d2_q}, {v2_q}), ({d3_q}, {v3_q})")
    print("2. System of Equations:")
    # Set up the 3 equations by plugging the x and y values into the quadratic formula
    print(f"   (Eq 1): a0 + {d1_q}*a1 + {d1_q**2}*a2 = {v1_q}")
    print(f"   (Eq 2): a0 + {d2_q}*a1 + {d2_q**2}*a2 = {v2_q}")
    print(f"   (Eq 3): a0 + {d3_q}*a1 + {d3_q**2}*a2 = {v3_q}\n")
    
    print("3. Gaussian Elimination:")
    
    # Forward Elimination Step 1: Eliminate 'a0' by subtracting adjacent equations.
    # Eq 2 - Eq 1 -> Creates Equation A
    c1_A = d2_q - d1_q                # Coefficient for a1
    c2_A = (d2_q**2) - (d1_q**2)      # Coefficient for a2
    ans_A = v2_q - v1_q               # Right side of the equation
    print(f"   Subtract Eq 1 from Eq 2 -> (Eq A): {c1_A}*a1 + {c2_A}*a2 = {ans_A:.2f}")
    
    # Eq 3 - Eq 2 -> Creates Equation B
    c1_B = d3_q - d2_q
    c2_B = (d3_q**2) - (d2_q**2)
    ans_B = v3_q - v2_q
    print(f"   Subtract Eq 2 from Eq 3 -> (Eq B): {c1_B}*a1 + {c2_B}*a2 = {ans_B:.2f}")
    
    # Forward Elimination Step 2: Eliminate 'a1' by subtracting Eq A from Eq B.
    # Because both Eq A and Eq B have 10*a1, subtracting them cancels out a1.
    c2_final = c2_B - c2_A
    ans_final = ans_B - ans_A
    print(f"   Subtract Eq A from Eq B -> {c2_final}*a2 = {ans_final:.2f}")
    
    print("\n4. Back-Substitution:")
    # Solve for a2 using the simplified final equation
    a2 = ans_final / c2_final
    print(f"   Find a2: {ans_final:.2f} / {c2_final} => a2 = {a2:.4f}")
    
    # Substitute a2 back into Equation A to solve for a1
    a1 = (ans_A - c2_A * a2) / c1_A
    print(f"   Find a1 (using Eq A): ({ans_A:.2f} - {c2_A}*{a2:.4f}) / {c1_A} => a1 = {a1:.3f}")
    
    # Substitute a1 and a2 back into Equation 1 to solve for a0
    a0 = v1_q - (d1_q * a1) - ((d1_q**2) * a2)
    print(f"   Find a0 (using Eq 1): {v1_q} - ({d1_q}*{a1:.3f}) - ({d1_q**2}*{a2:.4f}) => a0 = {a0:.2f}")
    
    print("\n5. Final Evaluation:")
    # Plug the target distance (55) into the newly found quadratic equation
    v_quad = a0 + a1 * d_target + a2 * (d_target**2)
    print(f"   V(55) = {a0:.2f} - {abs(a1):.3f}(55) + {a2:.4f}(55^2)")
    print(f"--> ANSWER: V(55) = {v_quad:.3f} V\n\n")


def solve_part_b():
    """Solves Part 2: Estimating the voltage at distance d = 94.5 cm.
       The logic is identical to Part A, but utilizes different starting data points."""
    print("==================================================")
    print("PART 2: Estimation at d = 94.5 cm")
    print("==================================================\n")
    
    # ==========================================
    # --- A. Linear Interpolation ---
    # Target is 94.5, so we use bounding points 90 cm and 100 cm.
    # ==========================================
    print("--- A. Linear Interpolation ---")
    d0, v0 = 90, 1.08
    d1, v1 = 100, 0.99
    d_target = 94.5
    
    print(f"1. Points used: ({d0}, {v0}) and ({d1}, {v1})")
    print(f"2. Formula: V(94.5) = {v0} + (({v1} - {v0}) / ({d1} - {d0})) * ({d_target} - {d0})")
    
    numerator = v1 - v0
    denominator = d1 - d0
    multiplier = d_target - d0
    slope = numerator / denominator
    
    print(f"3. Calculate slope: {numerator:.2f} / {denominator} = {slope:.3f}")
    v_linear = v0 + slope * multiplier
    print(f"4. Final Calculation: {v0} + ({slope:.3f} * {multiplier})")
    print(f"--> ANSWER: V(94.5) = {v_linear:.4f} V\n")
    
    # ==========================================
    # --- B. Quadratic Interpolation ---
    # Uses the 3 closest points to 94.5: 80 cm, 90 cm, and 100 cm.
    # ==========================================
    print("--- B. Quadratic Interpolation ---")
    d1_q, v1_q = 80, 1.18
    d2_q, v2_q = 90, 1.08
    d3_q, v3_q = 100, 0.99
    
    print(f"1. Points used: ({d1_q}, {v1_q}), ({d2_q}, {v2_q}), ({d3_q}, {v3_q})")
    print("2. System of Equations:")
    print(f"   (Eq 1): a0 + {d1_q}*a1 + {d1_q**2}*a2 = {v1_q}")
    print(f"   (Eq 2): a0 + {d2_q}*a1 + {d2_q**2}*a2 = {v2_q}")
    print(f"   (Eq 3): a0 + {d3_q}*a1 + {d3_q**2}*a2 = {v3_q}\n")
    
    print("3. Gaussian Elimination:")
    
    # Eliminate a0 (Eq 2 - Eq 1) -> Eq C
    c1_C = d2_q - d1_q
    c2_C = (d2_q**2) - (d1_q**2)
    ans_C = v2_q - v1_q
    print(f"   Subtract Eq 1 from Eq 2 -> (Eq C): {c1_C}*a1 + {c2_C}*a2 = {ans_C:.2f}")
    
    # Eliminate a0 (Eq 3 - Eq 2) -> Eq D
    c1_D = d3_q - d2_q
    c2_D = (d3_q**2) - (d2_q**2)
    ans_D = v3_q - v2_q
    print(f"   Subtract Eq 2 from Eq 3 -> (Eq D): {c1_D}*a1 + {c2_D}*a2 = {ans_D:.2f}")
    
    # Eliminate a1 (Eq D - Eq C)
    c2_final = c2_D - c2_C
    ans_final = ans_D - ans_C
    print(f"   Subtract Eq C from Eq D -> {c2_final}*a2 = {ans_final:.2f}")
    
    print("\n4. Back-Substitution:")
    # Solve for a2
    a2 = ans_final / c2_final
    print(f"   Find a2: {ans_final:.2f} / {c2_final} => a2 = {a2:.5f}")
    
    # Solve for a1
    a1 = (ans_C - c2_C * a2) / c1_C
    print(f"   Find a1 (using Eq C): ({ans_C:.2f} - {c2_C}*{a2:.5f}) / {c1_C} => a1 = {a1:.4f}")
    
    # Solve for a0
    a0 = v1_q - (d1_q * a1) - ((d1_q**2) * a2)
    print(f"   Find a0 (using Eq 1): {v1_q} - ({d1_q}*{a1:.4f}) - ({d1_q**2}*{a2:.5f}) => a0 = {a0:.2f}")
    
    print("\n5. Final Evaluation:")
    # Plug distance 94.5 into the resolved quadratic equation
    v_quad = a0 + a1 * d_target + a2 * (d_target**2)
    print(f"   V(94.5) = {a0:.2f} - {abs(a1):.4f}(94.5) + {a2:.5f}(94.5^2)")
    print(f"--> ANSWER: V(94.5) = {v_quad:.7f} V (Rounds to 1.0383 V)")

# --- Execute the code ---
# Calling these functions runs the print statements and math logic above.
solve_part_a()
solve_part_b()

PART 1: Estimation at d = 55 cm

--- A. Linear Interpolation ---
1. Points used: (50, 1.61) and (60, 1.44)
2. Formula: V(55) = 1.61 + ((1.44 - 1.61) / (60 - 50)) * (55 - 50)
3. Calculate slope: -0.17 / 10 = -0.017
4. Final Calculation: 1.61 + (-0.017 * 5)
--> ANSWER: V(55) = 1.525 V

--- B. Quadratic Interpolation ---
1. Points used: (40, 1.82), (50, 1.61), (60, 1.44)
2. System of Equations:
   (Eq 1): a0 + 40*a1 + 1600*a2 = 1.82
   (Eq 2): a0 + 50*a1 + 2500*a2 = 1.61
   (Eq 3): a0 + 60*a1 + 3600*a2 = 1.44

3. Gaussian Elimination:
   Subtract Eq 1 from Eq 2 -> (Eq A): 10*a1 + 900*a2 = -0.21
   Subtract Eq 2 from Eq 3 -> (Eq B): 10*a1 + 1100*a2 = -0.17
   Subtract Eq A from Eq B -> 200*a2 = 0.04

4. Back-Substitution:
   Find a2: 0.04 / 200 => a2 = 0.0002
   Find a1 (using Eq A): (-0.21 - 900*0.0002) / 10 => a1 = -0.039
   Find a0 (using Eq 1): 1.82 - (40*-0.039) - (1600*0.0002) => a0 = 3.06

5. Final Evaluation:
   V(55) = 3.06 - 0.039(55) + 0.0002(55^2)
--> ANSWER: V(55) = 1.520 V


